---
- name: Clona dotfiles
  git:
    repo: git@github.com:mbodock/dotfiles.git
    accept_hostkey: true
    dest: ~/.dotfiles/
    update: yes

- name: cria diretórios necessários
  file:
    path: ~/.config/fish
    state: directory

- name: Linka arquivos
  file:
    src: ~/.dotfiles/{{ item.src }}
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - {src: 'vimrc', dest: '~/.vimrc'}
    - {src: 'bashrc', dest: '~/.bashrc'}
    - {src: 'gitconfig', dest: '~/.gitconfig'}
    - {src: 'config.fish', dest: '~/.config/fish/config.fish'}
    - {src: 'tmux.conf', dest: '~/.tmux.conf'}
