- name: Instala fish shell
  apt:
      name: fish
      install_recommends: yes
  become: yes

- name: Cria pasta de configurações
  file:
      path: ~/.config/fish/
      state: directory

- name: Define fish como shell padrao
  user:
     name: "{{ ansible_ssh_user }}"
     shell: /usr/bin/fish
  become: yes
