---
- name: Adiciona repositórios
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: yes
  with_items:
    - ppa:nathan-renniewaldock/flux
    - ppa:jonathonf/vim
    - ppa:fossfreedom/arc-gtk-theme-daily

- name: Atualizar cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Atualizar pacotes
  apt:
    upgrade: dist
  become: yes

- name: Instala pacotes diários
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - arc-theme
    - aptitude
    - blueman
    - csvtool
    - dos2unix
    - etckeeper
    - flake8
    - fluxgui
    - gitg
    - gitinspector
    - gitk
    - glances
    - htop
    - iotop
    - lm-sensors
    - mplayer
    - mysql-workbench
    - openvpn
    - parcellite
    - pulseaudio-module-bluetooth
    - qbittorrent
    - ranger
    - recordmydesktop
    - shellcheck
    - tree
    - vagrant
    - vim
    - xclip
    - yamllint
    - zram-config

- name: Instala pacotes por deb
  apt:
    deb: "{{ item.url }}"
  become: yes
  with_items:
    - name: slack
      url: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb
